@startuml 1c-buh
'https://plantuml.com/sequence-diagram

autonumber

title Взаимодействия с внешними системами
actor Client as client
box "Система оформления заказов"
boundary "Mobile\nApp" as app
participant "API\nGateway" as apigw
participant "Orders\nService" as orders
participant "Payment\nService" as paymnent
participant "Message\nService" as message
endbox
database "File\nShare" as file
participant "1С Бухгал-\nтерия" as buh
participant "Процессинг\nБанка" as bank
participant "СМС\nШлюз" as sms

client->app: Создает заказ
apigw->orders++: GET \n ../nodegroups
@enduml