// Use DBML to define your database structure
// Docs: https://www.dbml.org/docs
// https://dbdiagram.io/d

Table orders {
  id int(4) [primary key]
  created_at timestamp(8)
  status smallint(2)
  client_id int(4)
  complectation int(4)
  delivered_at timestamp(8)
  sum decimal(8,2)
  bonuses_total int(4)
  bonuses_spent int(4)
  bonuses_valid timestamp(8)
}

Table order_items {  
  id int [primary key]
  order_id int(4)
  dish_id int(4)
  type smallint(2)
  quantity smallint(2)
  sum decimal(8,2)
  bonuses_total int(4)
  bonuses_spent int(4)
  bonuses_valid timestamp(8) 
}

Table basket {
  id int(4) [primary key]
  created_at timestamp(8)
  client_id int(4)
}

Table basket_items {  
  id int [primary key]
  basket_id int(4)
  dish_id int(4)
  type smallint(2)
  quantity smallint(2)
  sum decimal(8,2)
}

Table clients {
  id int(4) [primary key]
  created_at timestamp(8)
  surname varchar(20)
  name varchar(20)
  patronic varchar(20)
}

Table payments {
  id int(4) [primary key]
  created_at timestamp(8)
  order_id int(4)
  sum decimal(8,2)
  type smallint(2)
}

Table menus {
  id int(4) [primary key]
  created_at timestamp(8)
  name varchar(20)
  type smallint(2)
  active boolean(1)
  active_from date(3)
  active_to date(3)
}

Table menu_items {
  id int(4) [primary key]
  menu_id int(4)
  dish_id int(4)
}

Table dishes {
  id int(4) [primary key]
  name varchar(20)
  type smallint(2)
  description varchar(40)
  calorific integer(4)
  proteins decimal(3,1)
  fats decimal(3,1)
  carbs decimal(3,1)
  price decimal(8,2)
  photo varchar(256)  
}
Table ingredients {
  id int(4) [primary key]
  name varchar(20)
  mandatory boolean(1)
  max_qty smallint(2)
  calorific integer(4)
  proteins decimal(3,1)
  fats decimal(3,1)
  carbs decimal(3,1)
  price decimal(8,2)
  photo varchar(256)  
}

Table custom_dishes {
  id int(4) [primary key]
  ingredient_id int(4)
  quantity smallint(2)
  position smallint(2)
}

Table custom_dish_types {
  id int(4) [primary key]
  ingredient_id int(4)
  max_qty smallint(2)
}

Ref: orders.client_id > clients.id
Ref: payments.order_id > orders.id
Ref: basket.client_id > clients.id
Ref: order_items.order_id > orders.id
Ref: order_items.dish_id > dishes.id
Ref: basket_items.basket_id > basket.id
Ref: basket_items.dish_id > dishes.id
Ref: menu_items.menu_id > menus.id
Ref: menu_items.dish_id > dishes.id
Ref: custom_dishes.ingredient_id > ingredients.id
Ref: custom_dish_types.ingredient_id > ingredients.id




